#!/bin/sh

# Filename of directories to walk
filename="./directories.lst"

# Read directories from the file, line by line
tr -d '\r' <"$filename" | while read -r line; do
  # Find all subdirectories and remove a .gitkeep file if present
  # add -printf '%p\n' as an argument to find to print to terminal
  find "$line" -type d -exec sh -c 'rm -f "$1/.gitkeep"' sh {} ';'
done

exit 0